version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          - PUBSUB_EMULATOR_HOST: localhost:8085
      - image: google/cloud-sdk:452.0.1
        command:
          - gcloud
          - beta
          - emulators
          - pubsub
          - start
          - --host-port=0.0.0.0:8085
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec rake spec
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: rspec
      - run:
          command: bundle exec yardoc --fail-on-warning 'lib/**/*.rb'
      - store_artifacts:
          path: doc
