version: 2.1

orbs:
  ruby: circleci/ruby@1.7.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
        environment:
          - GEM_PATH: /home/circleci/project/vendor/bundle/ruby/3.0.0
          - PUBSUB_EMULATOR_HOST: localhost:8085
      - image: google/cloud-sdk:382.0.0
        command:
          - gcloud
          - beta
          - emulators
          - pubsub
          - start
          - --host-port=0.0.0.0:8085
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: RSpec
          # `bundle exec rspec` loads sparrow gem before simplecov starts that
          # prevents simplecov from gathering code coverage.
          command: rake spec
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: rspec
      - run:
          name: Yardoc
          command: bundle exec yardoc 'lib/**/*.rb'
      - store_artifacts:
          path: doc
