#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"
require "sentry-ruby"
require "sparrow"

Sentry.init

config = YAML.safe_load_file(ENV.fetch("SPARROW_CONFIG", nil))
master = Sparrow::Master.new(config)

%w[INT TERM].each do |signal|
  # Trap handlers cannot take locks, so stop from a thread.
  Signal.trap(signal) { Thread.new { master.stop } }
end

master.start
