name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
