name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
