name: docker push

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Docker Image to Docker Hub.
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: anipos/sparrow
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          tag_semver: true
