name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
