name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
