name: Docker Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
