name: Docker

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image.
      run: docker build .

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker Image to Docker Hub.
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: anipos/sparrow
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag_semver: true
      # Not to push from forked repositories.
      if: ${{ github.repository == 'anipos/sparrow' }}
